# Small model for single TPU v5e chip.

model:
  seqlen: 4096
  vocab_size: 50304
  d_emb: 768
  mlp_hidden_dim: 3072
  num_layers: 12
  q_heads: 8
  kv_heads: 8
  attn_impl: xla    # "flash_attn" or "xla"
  dtype: bfloat16

hparams:
  # Schedule
  total_train_steps: 5000
  warmup_steps: 150
  micro_batch_size: 16
  global_batch_size: 64

  # Optimizer
  max_lr: 6.0e-4
  min_lr: 6.0e-5
  embedding_lr: 0.2
  unembedding_lr: 0.004
  b1: 0.9
  b2: 0.95
  weight_decay: 0.01
  cautious_weight_decay: 0.0
  clip_grad_norm: 1.0

checkpoint:
  max_checkpoints_to_keep: 3
  checkpoint_save_steps: 100
  last_checkpoint_step: 0
  save_ckpt_dir: "checkpoints/small"
  load_params_ckpt_path: "checkpoints/small/5000/params"

profile:
  enabled: true
  profile_dir: "profiles/"
  start_step: 5
  end_step: 10

data_dir: "nanogpt/fineweb10B/"
