AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Before Architecture - Legacy Monolithic Web Application. Single-tier deployment with web, business logic, and data access on a single instance. No high availability, no auto scaling, no caching, and minimal observability.

Resources:
  # ---- Network Layer ----
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: legacy-vpc

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: legacy-public-subnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ---- Security ----
  MonolithSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH to monolith instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access from monolith only
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref MonolithSecurityGroup

  # ---- Compute: Single EC2 Instance (Web + App + Data Access) ----
  MonolithInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: m5.xlarge
      ImageId: ami-0abcdef1234567890
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref MonolithSecurityGroup
      Tags:
        - Key: Name
          Value: legacy-monolith
      UserData: !Base64 |
        #!/bin/bash
        # Manual deployment: operator SSHs in and deploys application
        echo "Monolith instance running web + business logic + data access"

  MonolithEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MonolithInstance

  # ---- Data: Single RDS Instance (No Multi-AZ, No Read Replicas) ----
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for legacy database
      SubnetIds:
        - !Ref PublicSubnet

  MonolithDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DBInstanceIdentifier: legacy-monolith-db
      DBInstanceClass: db.m5.large
      Engine: mysql
      EngineVersion: 8.0.42
      MasterUsername: admin
      MasterUserPassword: hardcoded-password-123
      AllocatedStorage: 100
      StorageType: gp2
      MultiAZ: false
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      BackupRetentionPeriod: 1
      Tags:
        - Key: Name
          Value: legacy-monolith-db

Outputs:
  ApplicationURL:
    Description: Public IP of the monolith application
    Value: !Sub http://${MonolithEIP}

  DatabaseEndpoint:
    Description: RDS endpoint for the monolithic database
    Value: !GetAtt MonolithDatabase.Endpoint.Address